language: ruby

before_script:  gem install rspec rspec-rails simplecov

script:
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec

rvm:
  - 2.2.0 

notifications:
  email:
    recipients:
      - jonatas_lenon@hotmail.com.br
      - danieelteles@gamil.com

branches:
  only:
  - dev