# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

	Grade.create(grade: "1° ano")
	Grade.create(grade: "2° ano")
	Grade.create(grade: "3° ano")
	Grade.create(grade: "4° ano")
	Grade.create(grade: "5° ano")
	Grade.create(grade: "6° ano")
	Grade.create(grade: "7° ano")
	Grade.create(grade: "8° ano")
	Grade.create(grade: "9° ano")

	State.create(state: "AC")
	State.create(state: "AL")
	State.create(state: "AP")
	State.create(state: "AM")
	State.create(state: "BA")
	State.create(state: "CE")
	State.create(state: "DF")
	State.create(state: "ES")
	State.create(state: "GO")
	State.create(state: "MA")
	State.create(state: "MT")
	State.create(state: "MS")
	State.create(state: "MG")
	State.create(state: "PA")
	State.create(state: "PB")
	State.create(state: "PR")
	State.create(state: "PE")
	State.create(state: "PI")
	State.create(state: "RJ")
	State.create(state: "RN")
	State.create(state: "RS")
	State.create(state: "RO")
	State.create(state: "RR")
	State.create(state: "SC")
	State.create(state: "SP")
	State.create(state: "SE")
	State.create(state: "TO")
